# Generated by Django 5.2.17 on 2026-08-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0011_seed_employment_retention_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.PositiveSmallIntegerField()),
                ('direction', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_created', to='core_hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core_hr.employee')),
                ('triggering_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_instances', to='core_hr.employmentchange')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('owner_role', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('line_manager', 'Line manager'), ('employee', 'Employee'), ('other', 'Other')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items_completed', to='core_hr.employee')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.checklistinstance')),
            ],
            options={
                'ordering': ['instance', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates_created', to='core_hr.employee')),
            ],
            options={
                'ordering': ['direction', 'name', '-version'],
            },
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='onboarding.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('owner_role', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('line_manager', 'Line manager'), ('employee', 'Employee'), ('other', 'Other')], default='hr', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.checklisttemplate')),
            ],
            options={
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('name', 'direction', 'version'), name='unique_checklist_template_name_direction_version'),
        ),
        migrations.AddConstraint(
            model_name='checklistinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('employee', 'direction'), name='one_active_checklist_per_employee_per_direction'),
        ),
    ]
