# Generated by Django 5.2.17 on 2026-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('pc_reminder', 'Performance reminder'), ('comp_approval', 'Compensation approval'), ('review_launch', 'Review stage opened'), ('policy_publish', 'Policy published'), ('liveness_flag', 'Liveness review flagged'), ('ee_signoff', 'Performance agreement signed'), ('contract_reminder', 'Contract expiry reminder')], max_length=30),
        ),
    ]
