# Generated by Django 5.2.17 on 2026-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
