# Generated by Django 5.2.17 on 2026-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_course_trainingrecord_course_courserequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='evidence_content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='training_evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='evidence_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='learner_agreement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='learning_programme_category',
            field=models.CharField(blank=True, choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D'), ('E', 'Category E'), ('F', 'Category F'), ('G', 'Category G')], max_length=1),
        ),
    ]
