# Generated by Django 5.2.17 on 2026-08-26 05:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('core_hr', '0016_alter_dataqualityexception_exception_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompCycle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical comp cycle',
                'verbose_name_plural': 'historical comp cycles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='compproposal',
            name='baseline_salary_at_proposal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='compproposal',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='compproposal',
            name='exceeds_cycle_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compproposal',
            name='proposal_type',
            field=models.CharField(choices=[('increase', 'Salary increase'), ('bonus', 'Bonus')], default='increase', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompproposal',
            name='baseline_salary_at_proposal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompproposal',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompproposal',
            name='exceeds_cycle_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompproposal',
            name='proposal_type',
            field=models.CharField(choices=[('increase', 'Salary increase'), ('bonus', 'Bonus')], default='increase', max_length=20),
        ),
        migrations.AlterField(
            model_name='compproposal',
            name='proposed_annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompproposal',
            name='proposed_annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='CompCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_cycles_closed', to='core_hr.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_cycles_created', to='core_hr.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_cycles', to='core_hr.department')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='compproposal',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='compensation.compcycle'),
        ),
        migrations.AddField(
            model_name='historicalcompproposal',
            name='cycle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compensation.compcycle'),
        ),
        migrations.AddConstraint(
            model_name='compproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bonus_amount__isnull', True), ('proposal_type', 'increase'), ('proposed_annual_salary__isnull', False)), models.Q(('bonus_amount__isnull', False), ('proposal_type', 'bonus'), ('proposed_annual_salary__isnull', True)), _connector='OR'), name='comp_proposal_amount_matches_type'),
        ),
        migrations.AddField(
            model_name='historicalcompcycle',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee'),
        ),
        migrations.AddField(
            model_name='historicalcompcycle',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee'),
        ),
        migrations.AddField(
            model_name='historicalcompcycle',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.department'),
        ),
        migrations.AddField(
            model_name='historicalcompcycle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='compcycle',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='compcycle_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='compcycle',
            constraint=models.CheckConstraint(condition=models.Q(('budget_amount__gte', 0)), name='compcycle_budget_non_negative'),
        ),
    ]
