# Generated by Django 5.2.17 on 2026-08-13 06:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0002_seed_occupational_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assessment_type', models.CharField(choices=[('cognitive', 'Cognitive ability'), ('personality', 'Personality profile'), ('technical', 'Technical / skills test'), ('other', 'Other')], max_length=20)),
                ('provider_key', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('access_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_assigned', to='core_hr.employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assignments', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_score', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessmentassignment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssessmentAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('applicant_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assessment_type', models.CharField(choices=[('cognitive', 'Cognitive ability'), ('personality', 'Personality profile'), ('technical', 'Technical / skills test'), ('other', 'Other')], max_length=20)),
                ('provider_key', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('access_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical assessment assignment',
                'verbose_name_plural': 'historical assessment assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['provider_key'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_provider')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applicant_id__isnull', True), ('employee__isnull', False)), models.Q(('applicant_id__isnull', False), ('employee__isnull', True)), _connector='OR'), name='assessmentassignment_exactly_one_subject'),
        ),
    ]
