# Generated by Django 5.2.17 on 2026-08-27 05:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee_reporting', '0004_seed_report_retention_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EESector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('targets', models.JSONField(default=dict)),
                ('disability_target_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='employerconfig',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='ee_reporting.eesector'),
        ),
        migrations.AddField(
            model_name='historicalemployerconfig',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ee_reporting.eesector'),
        ),
    ]
