# Generated by Django 5.2.17 on 2026-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplicant',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
