# Generated by Django 5.2.17 on 2026-08-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_backfill_existing_employees'),
        ('recruitment', '0002_applicant_anonymised_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='requisitions', to='establishment.position'),
        ),
    ]
