# Generated by Django 6.1 on 2026-08-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0002_seed_occupational_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=200, unique=True)),
                ('period_months', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('anonymise', 'Anonymise'), ('delete', 'Delete'), ('retain', 'Retain indefinitely')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['entity_type'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('row_scope', models.CharField(choices=[('all', 'All records'), ('own_team', 'Own team (reporting line)'), ('self', 'Self only')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('demographic_self_id', 'Demographic self-identification'), ('assessment', 'Psychometric assessment'), ('other', 'Other')], max_length=30)),
                ('lawful_basis', models.CharField(choices=[('consent', 'Consent'), ('legal_obligation_eea', 'Legal obligation (Employment Equity Act)')], max_length=30)),
                ('granted_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('text_version', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read_sensitive', 'Read sensitive/restricted field(s)'), ('access_denied', 'Access denied'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('login', 'Login'), ('permission_change', 'Permission change')], max_length=30)),
                ('entity_type', models.CharField(max_length=200)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('field_tier', models.CharField(choices=[('P', 'Public'), ('I', 'Internal'), ('S', 'Sensitive'), ('R', 'Restricted')], max_length=1)),
                ('fields_touched', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='rbac_audit__actor_i_d02c39_idx'), models.Index(fields=['entity_type', 'entity_id'], name='rbac_audit__entity__1ff34b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core_hr.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to='core_hr.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rbac_audit.role')),
            ],
            options={
                'ordering': ['employee', 'role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('employee', 'role'), name='one_active_assignment_per_employee_role')],
            },
        ),
        migrations.CreateModel(
            name='RoleFieldTierGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('P', 'Public'), ('I', 'Internal'), ('S', 'Sensitive'), ('R', 'Restricted')], max_length=1)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_grants', to='rbac_audit.role')),
            ],
            options={
                'ordering': ['role', 'tier'],
                'constraints': [models.UniqueConstraint(fields=('role', 'tier'), name='one_grant_per_role_tier')],
            },
        ),
    ]
