# Generated by Django 5.2.17 on 2026-08-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0002_seed_occupational_levels'),
        ('rbac_audit', '0002_seed_roles'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='recruitment.applicant'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core_hr.employee'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applicant__isnull', True), ('employee__isnull', False)), models.Q(('applicant__isnull', False), ('employee__isnull', True)), _connector='OR'), name='consentrecord_exactly_one_subject'),
        ),
    ]
