# Generated by Django 5.2.17 on 2026-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_audit', '0003_consentrecord_applicant_alter_consentrecord_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose',
            field=models.CharField(choices=[('demographic_self_id', 'Demographic self-identification'), ('assessment', 'Psychometric assessment'), ('biometric', 'Biometric identity + attendance-location verification'), ('other', 'Other')], max_length=30),
        ),
    ]
