# Generated by Django 5.2.17 on 2026-08-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0003_historicallocation_latitude_and_more'),
        ('rbac_audit', '0005_seed_accounting_officer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('read_sensitive', 'Read sensitive/restricted field(s)'), ('access_denied', 'Access denied'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('login', 'Login'), ('permission_change', 'Permission change'), ('step_up_granted', 'Step-up authentication granted')], max_length=30),
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to='core_hr.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepUpGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('payroll_data', 'Payroll / compensation data')], max_length=30)),
                ('reason', models.CharField(choices=[('payroll_processing', 'Payroll processing or audit'), ('employee_query', 'Employee query or dispute resolution'), ('compliance_reporting', 'Compliance or regulatory reporting'), ('system_troubleshooting', 'System troubleshooting'), ('other', 'Other (specify)')], max_length=30)),
                ('reason_detail', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_grants', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['employee', 'scope', 'expires_at'], name='rbac_audit__employe_c45e0b_idx')],
            },
        ),
    ]
