# Generated by Django 5.2.17 on 2026-08-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_audit', '0007_seed_default_retention_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'ordering': ['-timestamp', '-id']},
        ),
    ]
