# Generated by Django 5.2.17 on 2026-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_audit', '0008_alter_auditlogentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose',
            field=models.CharField(choices=[('demographic_self_id', 'Demographic self-identification'), ('assessment', 'Psychometric assessment'), ('biometric', 'Biometric identity + attendance-location verification'), ('employee_documents', 'Employee document storage (ID copy, disability verification)'), ('other', 'Other')], max_length=30),
        ),
    ]
