# Generated by Django 5.2.17 on 2026-09-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_audit', '0010_seed_policy_committee_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRuleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('period_months', models.PositiveIntegerField()),
                ('cutoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('skipped', 'Skipped'), ('no_handler', 'No handler registered'), ('error', 'Error')], max_length=20)),
                ('affected', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_runs', to='rbac_audit.retentionrun')),
            ],
            options={
                'ordering': ['entity_type'],
            },
        ),
    ]
