# Generated by Django 5.2.17 on 2026-09-03 17:18

import rbac_audit.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_audit', '0011_retentionrun_retentionrulerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='totpdevice',
            name='secret_encrypted',
            field=rbac_audit.fields.EncryptedCharField(blank=True, default='', max_length=500, purpose='totp_seed'),
        ),
    ]
