# Generated by Django 5.2.17 on 2026-08-25 08:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0012_dependant_emergencycontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('id_copy', 'ID copy'), ('qualification', 'Qualification / certificate'), ('employment_contract', 'Employment contract'), ('disability_verification', 'Disability verification'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core_hr.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_documents_uploaded', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('document_type', models.CharField(choices=[('id_copy', 'ID copy'), ('qualification', 'Qualification / certificate'), ('employment_contract', 'Employment contract'), ('disability_verification', 'Disability verification'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.TextField(max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
            ],
            options={
                'verbose_name': 'historical employee document',
                'verbose_name_plural': 'historical employee documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('export', 'Export my data'), ('erasure', 'Erasure request')], max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('completed', 'Completed'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='data_subject_exports/%Y/%m/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject_requests', to='core_hr.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_subject_requests_filed', to='core_hr.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_subject_requests_reviewed', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'submitted')), fields=('employee', 'request_type'), name='one_open_data_subject_request_per_employee_per_type')],
            },
        ),
    ]
