# Generated by Django 5.2.17 on 2026-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_retention_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubjectrequest',
            name='export_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datasubjectrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('completed', 'Completed'), ('partially_completed', 'Partially completed'), ('declined', 'Declined')], default='submitted', max_length=20),
        ),
    ]
