# Generated by Django 5.2.17 on 2026-08-13 17:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0003_historicallocation_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPolicy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('code_of_conduct', 'Code of Conduct'), ('leave', 'Leave Policy'), ('it_acceptable_use', 'IT Acceptable Use'), ('anti_harassment', 'Anti-Harassment & Anti-Discrimination'), ('health_safety', 'Health & Safety'), ('remote_work', 'Remote Work'), ('popia_privacy', 'POPIA / Data Privacy'), ('other', 'Other')], default='other', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
            ],
            options={
                'verbose_name': 'historical policy',
                'verbose_name_plural': 'historical policys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('code_of_conduct', 'Code of Conduct'), ('leave', 'Leave Policy'), ('it_acceptable_use', 'IT Acceptable Use'), ('anti_harassment', 'Anti-Harassment & Anti-Discrimination'), ('health_safety', 'Health & Safety'), ('remote_work', 'Remote Work'), ('popia_privacy', 'POPIA / Data Privacy'), ('other', 'Other')], default='other', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_created', to='core_hr.employee')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_published', to='core_hr.employee')),
            ],
            options={
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='core_hr.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgments', to='policies.policy')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_policy_code_version'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgment',
            constraint=models.UniqueConstraint(fields=('employee', 'policy'), name='one_acknowledgment_per_employee_per_policy_version'),
        ),
    ]
