# Generated by Django 5.2.17 on 2026-08-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicy',
            name='source_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='policy_documents/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PolicyChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='policies.policy')),
            ],
            options={
                'ordering': ['policy', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'sequence'), name='unique_policy_chunk_sequence')],
            },
        ),
    ]
