# Generated by Django 5.2.17 on 2026-09-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0020_historicalprobationreview_employee_signature_sha256_and_more'),
        ('policies', '0002_historicalpolicy_source_file_policy_source_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_hr.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='policies.policy')),
            ],
            options={
                'ordering': ['-approved_at'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'approved_by'), name='one_approval_per_committee_member_per_policy')],
            },
        ),
    ]
