# Generated by Django 5.2.17 on 2026-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricenrollment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbiometricenrollment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
