# Generated by Django 5.2.17 on 2026-08-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0004_collab_ids'),
        ('performance', '0002_performance_agreements'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('contracting', 'Contracting'), ('midyear', 'Mid-year review (Q2)'), ('final', 'Final assessment (Q4)')], max_length=20)),
                ('kind', models.CharField(choices=[('file', 'Uploaded file'), ('link', 'Link (OneDrive / SharePoint / Teams / other)')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='performance_evidence/%Y/%m/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('added_after_signoff', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='performance.agreementelement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items_uploaded', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
