# Generated by Django 5.2.17 on 2026-08-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0004_collab_ids'),
        ('performance', '0003_performance_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reasons', models.TextField()),
                ('actions', models.TextField()),
                ('review_date', models.DateField()),
                ('outcome', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='performance.performanceagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_plans_created', to='core_hr.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvement_plans_owned', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
