# Generated by Django 5.2.17 on 2026-08-25 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0015_alter_dataqualityexception_exception_type'),
        ('performance', '0004_improvementplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=20)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('participants_note', models.CharField(blank=True, help_text='Free text: who attended (Heads/managers)', max_length=500)),
                ('summary', models.TextField(blank=True, help_text="Overall committee notes, e.g. 'distribution reviewed, no changes needed'")),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('convened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_sessions_convened', to='core_hr.employee')),
                ('department', models.ForeignKey(blank=True, help_text='Blank = org-wide cohort', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_sessions', to='core_hr.department')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_sessions', to='performance.performanceperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback360Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='performance.performanceagreement')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests_opened', to='core_hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback360Rater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager / Head'), ('peer', 'Peer'), ('direct_report', 'Direct report')], max_length=20)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved — invited'), ('declined_nomination', 'Nomination declined'), ('withdrawn', 'Withdrawn')], default='pending_approval', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_360_raters_approved', to='core_hr.employee')),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_360_raters_nominated', to='core_hr.employee')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_360_rater_assignments', to='core_hr.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raters', to='performance.feedback360request')),
            ],
            options={
                'ordering': ['request', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback360Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True)),
                ('development_areas', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rater_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='performance.feedback360rater')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reason', models.TextField()),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_adjustments_made', to='core_hr.employee')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_adjustments', to='performance.performanceagreement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='performance.calibrationsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'agreement'), name='one_calibration_outcome_per_agreement')],
            },
        ),
        migrations.AddConstraint(
            model_name='feedback360rater',
            constraint=models.UniqueConstraint(fields=('request', 'rater'), name='one_rater_slot_per_request'),
        ),
    ]
