# Generated by Django 5.2.17 on 2026-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0002_seed_occupational_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
