# Generated by Django 5.2.17 on 2026-08-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0003_historicallocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='collab_department_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='collab_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='collab_department_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='collab_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
