# Generated by Django 5.2.17 on 2026-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0004_collab_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityexception',
            name='exception_type',
            field=models.CharField(choices=[('missing_grade', 'Missing job grade'), ('missing_demographics', 'Missing demographics'), ('orphan_record', 'Orphan record (no version history)'), ('performance_overdue', 'Overdue performance stage'), ('comp_proposal_stale', 'Compensation proposal awaiting review too long')], max_length=30),
        ),
    ]
