# Generated by Django 5.2.17 on 2026-08-19 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_alter_dataqualityexception_exception_type'),
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeversion',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_versions', to='establishment.position'),
        ),
        migrations.AddField(
            model_name='historicalemployeeversion',
            name='position',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establishment.position'),
        ),
    ]
