# Generated by Django 5.2.17 on 2026-08-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0006_employeeversion_position_and_more'),
        ('establishment', '0002_backfill_existing_employees'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('position',), name='one_current_occupant_per_position'),
        ),
    ]
