# Generated by Django 5.2.17 on 2026-08-20 10:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0007_employeeversion_one_current_occupant_per_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeversion',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeversion',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataqualityexception',
            name='exception_type',
            field=models.CharField(choices=[('missing_grade', 'Missing job grade'), ('missing_demographics', 'Missing demographics'), ('orphan_record', 'Orphan record (no version history)'), ('missing_contract_end_date', 'Fixed-term employee missing contract end date'), ('performance_overdue', 'Overdue performance stage'), ('comp_proposal_stale', 'Compensation proposal awaiting review too long')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employmentevent',
            name='event_type',
            field=models.CharField(choices=[('hire', 'Hire'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('grade_change', 'Grade change'), ('termination', 'Termination'), ('contract_conversion', 'Contract conversion'), ('contract_renewal', 'Contract renewal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalemploymentevent',
            name='event_type',
            field=models.CharField(choices=[('hire', 'Hire'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('grade_change', 'Grade change'), ('termination', 'Termination'), ('contract_conversion', 'Contract conversion'), ('contract_renewal', 'Contract renewal')], max_length=30),
        ),
        migrations.CreateModel(
            name='ContractRenewalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('decided', 'Decided')], max_length=20)),
                ('recommended_action', models.CharField(blank=True, choices=[('renew', 'Renew'), ('convert_permanent', 'Convert to permanent'), ('let_lapse', 'Let lapse')], max_length=20, null=True)),
                ('recommended_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_comment', models.TextField(blank=True)),
                ('recommended_end_date', models.DateField(blank=True, null=True)),
                ('decided_action', models.CharField(blank=True, choices=[('renew', 'Renew'), ('convert_permanent', 'Convert to permanent'), ('let_lapse', 'Let lapse')], max_length=20, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_comment', models.TextField(blank=True)),
                ('decided_end_date', models.DateField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_hr.employee')),
                ('employee_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_renewal_decision', to='core_hr.employeeversion')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_hr.employee')),
                ('resulting_employee_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.employeeversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalContractRenewalDecision',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('decided', 'Decided')], max_length=20)),
                ('recommended_action', models.CharField(blank=True, choices=[('renew', 'Renew'), ('convert_permanent', 'Convert to permanent'), ('let_lapse', 'Let lapse')], max_length=20, null=True)),
                ('recommended_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_comment', models.TextField(blank=True)),
                ('recommended_end_date', models.DateField(blank=True, null=True)),
                ('decided_action', models.CharField(blank=True, choices=[('renew', 'Renew'), ('convert_permanent', 'Convert to permanent'), ('let_lapse', 'Let lapse')], max_length=20, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_comment', models.TextField(blank=True)),
                ('decided_end_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('employee_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employeeversion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('resulting_employee_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employeeversion')),
            ],
            options={
                'verbose_name': 'historical contract renewal decision',
                'verbose_name_plural': 'historical contract renewal decisions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
