# Generated by Django 5.2.17 on 2026-08-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0008_employeeversion_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractrenewaldecision',
            options={'ordering': ['-created_at']},
        ),
    ]
