# Generated by Django 5.2.17 on 2026-08-21 09:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0009_contractrenewaldecision_ordering'),
        ('rbac_audit', '0008_alter_auditlogentry_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('suspension', 'Suspension'), ('lift_suspension', 'Lift suspension'), ('dismissal_summary', 'Summary dismissal'), ('dismissal_misconduct', 'Dismissal — misconduct'), ('dismissal_incapacity', 'Dismissal — incapacity'), ('operational_requirements', 'Operational requirements'), ('resignation', 'Resignation'), ('retirement', 'Retirement'), ('contract_end', 'Contract end'), ('death', 'Death')], max_length=30)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('proposed_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_hr.employee')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_changes', to='core_hr.employee')),
                ('lifts_suspension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifted_by', to='core_hr.employmentchange')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_hr.employee')),
                ('resulting_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_change', to='core_hr.employmentevent')),
                ('revoked_role_assignments', models.ManyToManyField(blank=True, related_name='revoked_by_employment_changes', to='rbac_audit.roleassignment')),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmploymentChange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('change_type', models.CharField(choices=[('suspension', 'Suspension'), ('lift_suspension', 'Lift suspension'), ('dismissal_summary', 'Summary dismissal'), ('dismissal_misconduct', 'Dismissal — misconduct'), ('dismissal_incapacity', 'Dismissal — incapacity'), ('operational_requirements', 'Operational requirements'), ('resignation', 'Resignation'), ('retirement', 'Retirement'), ('contract_end', 'Contract end'), ('death', 'Death')], max_length=30)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('proposed_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('confirmed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lifts_suspension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employmentchange')),
                ('proposed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('resulting_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employmentevent')),
            ],
            options={
                'verbose_name': 'historical employment change',
                'verbose_name_plural': 'historical employment changes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='employmentchange',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['proposed', 'confirmed'])), fields=('employee',), name='one_open_employment_change_per_employee'),
        ),
    ]
