# Generated by Django 5.2.17 on 2026-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0014_alter_dataqualityexception_exception_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityexception',
            name='exception_type',
            field=models.CharField(choices=[('missing_grade', 'Missing job grade'), ('missing_demographics', 'Missing demographics'), ('orphan_record', 'Orphan record (no version history)'), ('missing_contract_end_date', 'Fixed-term employee missing contract end date'), ('performance_overdue', 'Overdue performance stage'), ('comp_proposal_stale', 'Compensation proposal awaiting review too long'), ('mandatory_training_overdue', 'Overdue mandatory training'), ('critical_post_no_successor', 'Critical post without a ready successor'), ('performance_no_calibration', 'Final-signed agreement with no calibration session')], max_length=30),
        ),
    ]
