# Generated by Django 5.2.17 on 2026-08-27 10:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0018_historicalprobationperiod_probationperiod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateField()),
                ('primary_reason', models.CharField(choices=[('compensation', 'Compensation'), ('career_growth', 'Career growth'), ('management', 'Management or relationship with manager'), ('work_life_balance', 'Work-life balance'), ('relocation', 'Relocation'), ('health', 'Health or personal'), ('role_fit', 'Role fit'), ('other', 'Other')], max_length=30)),
                ('would_recommend_employer', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_interviews_conducted', to='core_hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='core_hr.employee')),
                ('employment_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews', to='core_hr.employmentchange')),
                ('probation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews', to='core_hr.probationperiod')),
            ],
            options={
                'ordering': ['-interview_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExitInterview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('interview_date', models.DateField()),
                ('primary_reason', models.CharField(choices=[('compensation', 'Compensation'), ('career_growth', 'Career growth'), ('management', 'Management or relationship with manager'), ('work_life_balance', 'Work-life balance'), ('relocation', 'Relocation'), ('health', 'Health or personal'), ('role_fit', 'Role fit'), ('other', 'Other')], max_length=30)),
                ('would_recommend_employer', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conducted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('employment_change', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employmentchange')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('probation_period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.probationperiod')),
            ],
            options={
                'verbose_name': 'historical exit interview',
                'verbose_name_plural': 'historical exit interviews',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
