# Generated by Django 5.2.17 on 2026-08-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0019_exitinterview_historicalexitinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprobationreview',
            name='employee_signature_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='probationreview',
            name='employee_signature_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
