# Generated by Django 5.2.17 on 2026-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0020_historicalprobationreview_employee_signature_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentchange',
            name='exit_handler_effects',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employmentchange',
            name='login_disabled_by_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemploymentchange',
            name='exit_handler_effects',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalemploymentchange',
            name='login_disabled_by_change',
            field=models.BooleanField(default=False),
        ),
    ]
