# Generated by Django 5.2.17 on 2026-09-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0021_employmentchange_exit_handler_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentchange',
            name='access_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalemploymentchange',
            name='access_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AccessRevocationObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('employment_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocation_obligations', to='core_hr.employmentchange')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employment_change', 'domain'), name='one_obligation_per_change_domain')],
            },
        ),
    ]
