# Generated by Django 5.2.17 on 2026-09-03 17:18

import rbac_audit.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0022_employmentchange_access_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_id_number_encrypted',
            field=rbac_audit.fields.EncryptedCharField(blank=True, default='', max_length=500, purpose='national_id'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number_encrypted',
            field=rbac_audit.fields.EncryptedCharField(blank=True, default='', max_length=500, purpose='passport_number'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='national_id_number_encrypted',
            field=rbac_audit.fields.EncryptedCharField(blank=True, default='', max_length=500, purpose='national_id'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='passport_number_encrypted',
            field=rbac_audit.fields.EncryptedCharField(blank=True, default='', max_length=500, purpose='passport_number'),
        ),
    ]
